# JWT Configuration
JWT:
  SECRET_KEY: ""
  REFRESH_TOKEN_EXPIRE:
  ACCESS_TOKEN_EXPIRE:

# Database Configurations
SQLALCHEMY_DATABASE_URI: ""
SQLALCHEMY_TRACK_MODIFICATIONS: False
SQLALCHEMY_ENGINE_OPTIONS: { "isolation_level": "AUTOCOMMIT" }